version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - echo "Node version:" $(node --version)
      - echo "NPM version:" $(npm --version)

  build:
    commands:
      - echo "Building the application..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "Syncing to S3 bucket..."
      # Upload all files with long cache except index.html and remoteEntry.js
      - |
        aws s3 sync dist/ s3://${S3_BUCKET_NAME} \
          --delete \
          --cache-control "public, max-age=31536000, immutable" \
          --exclude "index.html" \
          --exclude "remoteEntry.js"
      
      # Upload index.html with no cache
      - |
        aws s3 cp dist/index.html s3://${S3_BUCKET_NAME}/index.html \
          --cache-control "public, max-age=0, must-revalidate"
      
      # Upload remoteEntry.js with short cache
      - |
        if [ -f dist/assets/remoteEntry.js ]; then
          aws s3 cp dist/assets/remoteEntry.js s3://${S3_BUCKET_NAME}/assets/remoteEntry.js \
            --cache-control "public, max-age=300" \
            --content-type "application/javascript"
        fi
      
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
